name: Docker Build and Deploy

on:
  push:
    branches:
      - github-action/pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: cloudlearningsdocker/python-flask-app:latest

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v3

  #   - name: Pull Docker Image Locally
  #     run: docker pull cloudlearningdocker/python-flask-app:latest

  #   - name: Run Docker Container Locally
  #     run: docker run -d -p 5000:5000 your-dockerhub-username/your-image-name:latest
